# Generated by Django 5.2.15 on 2026-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('directory', '0006_remove_territorialorganphotofolder_unique_root_photo_folder_per_organ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='код активации'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='allowed_profiles', to='directory.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
    ]
