# Generated by Django 5.2.15 on 2026-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
