# Generated by Django 5.2.15 on 2026-06-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialOrganPhotoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('territorial_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_folders', to='directory.territorialorgan', verbose_name='территориальный орган')),
            ],
            options={
                'verbose_name': 'папка фотографий',
                'verbose_name_plural': 'папки фотографий',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='territorialorganphoto',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='directory.territorialorganphotofolder', verbose_name='папка'),
        ),
        migrations.AddIndex(
            model_name='territorialorganphoto',
            index=models.Index(fields=['territorial_organ', 'folder', 'is_deleted'], name='directory_t_territo_c63da5_idx'),
        ),
        migrations.AddConstraint(
            model_name='territorialorganphotofolder',
            constraint=models.UniqueConstraint(fields=('territorial_organ', 'name'), name='unique_photo_folder_per_organ'),
        ),
    ]
