# Generated by Django 5.2.15 on 2026-06-27 08:22

from pathlib import Path

from django.db import migrations, models


def populate_original_filename(apps, schema_editor):
    photo_model = apps.get_model("directory", "TerritorialOrganPhoto")
    for photo in photo_model.objects.exclude(image="").iterator():
        filename = Path(photo.image.name).name
        if filename:
            photo.original_filename = filename
            photo.save(update_fields=["original_filename"])


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_territorialorganphotofolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialorganphoto',
            name='original_filename',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='имя файла'),
        ),
        migrations.RunPython(populate_original_filename, migrations.RunPython.noop),
    ]
