# Generated by Django 5.2.15 on 2026-06-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_territorialorganphoto_original_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territorialorganphoto',
            options={'ordering': ('-created_at',), 'verbose_name': 'фотография территориального органа', 'verbose_name_plural': 'фотографии территориальных органов'},
        ),
        migrations.RemoveField(
            model_name='territorialorganphoto',
            name='photo_date',
        ),
    ]
