# Generated by Django 5.2.15 on 2026-06-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_territorialorganphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='territorialorganphotofolder',
            name='unique_photo_folder_per_organ',
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.territorialorganphotofolder', verbose_name='родительская папка'),
        ),
        migrations.AddIndex(
            model_name='territorialorganphotofolder',
            index=models.Index(fields=['territorial_organ', 'parent', 'name'], name='directory_t_territo_6d07b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='territorialorganphotofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('territorial_organ', 'name'), name='unique_root_photo_folder_per_organ'),
        ),
        migrations.AddConstraint(
            model_name='territorialorganphotofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('territorial_organ', 'parent', 'name'), name='unique_child_photo_folder_per_parent'),
        ),
    ]
