# Generated by Django 5.2.15 on 2026-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_remove_territorialorganphotofolder_unique_photo_folder_per_organ_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='territorialorganphotofolder',
            name='unique_root_photo_folder_per_organ',
        ),
        migrations.RemoveConstraint(
            model_name='territorialorganphotofolder',
            name='unique_child_photo_folder_per_parent',
        ),
        migrations.RemoveIndex(
            model_name='territorialorganphotofolder',
            name='directory_t_territo_6d07b8_idx',
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='удалено'),
        ),
        migrations.AddIndex(
            model_name='territorialorganphotofolder',
            index=models.Index(fields=['territorial_organ', 'parent', 'is_deleted', 'name'], name='directory_t_territo_323c6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='territorialorganphotofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', True)), fields=('territorial_organ', 'name'), name='unique_root_photo_folder_per_organ'),
        ),
        migrations.AddConstraint(
            model_name='territorialorganphotofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('parent__isnull', False)), fields=('territorial_organ', 'parent', 'name'), name='unique_child_photo_folder_per_parent'),
        ),
    ]
