# Generated by Django 5.2.15 on 2026-07-02 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_remove_territorialorganphotofolder_unique_root_photo_folder_per_organ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialorganphoto',
            name='created_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photos', to='directory.department', verbose_name='отдел автора'),
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photo_folders', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='created_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photo_folders', to='directory.department', verbose_name='отдел автора'),
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AddField(
            model_name='territorialorganphotofolder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_photo_folders', to=settings.AUTH_USER_MODEL, verbose_name='обновил'),
        ),
    ]
