# Generated by Django 5.2.15 on 2026-07-05 13:18

import mimetypes

import django.core.validators
from django.db import migrations, models


def populate_photo_metadata(apps, schema_editor):
    photo_model = apps.get_model("directory", "TerritorialOrganPhoto")
    for photo in photo_model.objects.exclude(image="").iterator():
        file_size = 0
        try:
            file_size = photo.image.size or 0
        except (OSError, ValueError):
            file_size = 0
        mime_type = mimetypes.guess_type(photo.image.name)[0] or ""
        photo.file_size = file_size
        photo.mime_type = mime_type[:100]
        photo.save(update_fields=["file_size", "mime_type"])


def clear_photo_metadata(apps, schema_editor):
    photo_model = apps.get_model("directory", "TerritorialOrganPhoto")
    photo_model.objects.update(file_size=0, mime_type="")


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_territorialorganphoto_created_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialorganphoto',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='размер файла, байт'),
        ),
        migrations.AddField(
            model_name='territorialorganphoto',
            name='mime_type',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='MIME-тип'),
        ),
        migrations.RunPython(populate_photo_metadata, clear_photo_metadata),
        migrations.AlterField(
            model_name='territorialorgan',
            name='order_number',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='номер'),
        ),
        migrations.AddConstraint(
            model_name='territorialorgan',
            constraint=models.CheckConstraint(condition=models.Q(('order_number__gte', 0)), name='territorial_organ_order_non_negative'),
        ),
    ]
