# Generated by Django 5.2.15 on 2026-07-05 13:32

import apps.directory.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_territorialorganphoto_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorialorganphoto',
            name='image',
            field=models.ImageField(upload_to='territorial_organs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.directory.models.validate_photo_size, apps.directory.models.validate_photo_content], verbose_name='изображение'),
        ),
    ]
