# Generated by Django 5.2.15 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_alter_territorialorganphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialorganphoto',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, editable=False, upload_to='', verbose_name='миниатюра 640px'),
        ),
        migrations.AddField(
            model_name='territorialorganphoto',
            name='thumbnail_small',
            field=models.ImageField(blank=True, editable=False, upload_to='', verbose_name='миниатюра 160px'),
        ),
    ]
