# Generated by Django 5.2.15 on 2026-07-10 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('directory', '0010_territorialorganphoto_thumbnails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['territorial_organ', 'created_at'], name='audit_audit_territo_b41ede_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'),
        ),
    ]
