# Generated by Django 5.2.15 on 2026-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('record_created', 'Создание записи'), ('record_updated', 'Изменение записи'), ('moved_to_trash', 'Перемещение в корзину'), ('request_restored_from_trash', 'Восстановление заявки'), ('photo_restored_from_trash', 'Восстановление фотографии'), ('photo_folder_tree_restored_from_trash', 'Восстановление папки'), ('photo_file_permanently_deleted', 'Окончательное удаление фотографии'), ('photo_folder_tree_permanently_deleted', 'Окончательное удаление папки'), ('request_status_changed', 'Изменение статуса заявки'), ('request_photos_attached', 'Прикрепление фотографий'), ('request_photos_detached', 'Открепление фотографий'), ('tmc_item_added', 'Добавление позиции ТМЦ'), ('tmc_item_removed', 'Удаление позиции ТМЦ'), ('tmc_item_quantity_changed', 'Изменение количества ТМЦ'), ('tmc_product_created', 'Добавление наименования ТМЦ'), ('employee_created', 'Создание сотрудника'), ('employee_permissions_updated', 'Изменение прав сотрудника'), ('employee_blocked', 'Блокировка сотрудника'), ('employee_unblocked', 'Разблокировка сотрудника'), ('employee_activation_reset', 'Сброс активации сотрудника'), ('employee_deleted', 'Удаление сотрудника'), ('account_activated', 'Активация учётной записи'), ('settings_updated', 'Изменение настроек'), ('settings_reset', 'Сброс настроек'), ('password_changed', 'Смена пароля'), ('table_exported', 'Экспорт таблицы'), ('photo_downloaded', 'Скачивание фотографии'), ('photo_archive_downloaded', 'Скачивание архива фотографий'), ('personal_trash_item_removed', 'Удаление из личной корзины'), ('personal_trash_cleared', 'Очистка личной корзины'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], db_index=True, max_length=64, verbose_name='тип события'),
        ),
    ]
