# Generated by Django 5.2.15 on 2026-06-27 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_tmc_history_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleinventory',
            options={'ordering': ('-state_date', '-created_at'), 'verbose_name': 'автотранспорт', 'verbose_name_plural': 'Автотранспорт'},
        ),
        migrations.AddField(
            model_name='vehicleinventory',
            name='state_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
    ]
