# Generated by Django 5.2.15 on 2026-06-27 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_vehicle_repair_history(apps, schema_editor):
    VehicleRepairRequest = apps.get_model("requests_app", "VehicleRepairRequest")
    VehicleRepairRequestStatusHistory = apps.get_model("requests_app", "VehicleRepairRequestStatusHistory")
    history = [
        VehicleRepairRequestStatusHistory(
            request=request,
            old_status=None,
            new_status=request.status,
            completed_at=request.completed_at if request.status == "done" else None,
            changed_by=request.created_by,
            note="Создание заявки",
        )
        for request in VehicleRepairRequest.objects.filter(is_deleted=False)
    ]
    VehicleRepairRequestStatusHistory.objects.bulk_create(history, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_alter_vehicleinventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepairrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки'),
        ),
        migrations.CreateModel(
            name='VehicleRepairRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, null=True, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, verbose_name='новый статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата изменения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_repair_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.vehiclerepairrequest', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'изменение статуса заявки на ремонт автотранспорта',
                'verbose_name_plural': 'История статусов заявок на ремонт автотранспорта',
                'ordering': ('-changed_at', '-id'),
                'indexes': [models.Index(fields=['request', '-changed_at'], name='requests_ap_request_0e1187_idx')],
            },
        ),
        migrations.RunPython(create_initial_vehicle_repair_history, migrations.RunPython.noop),
    ]
