# Generated by Django 5.2.15 on 2026-06-27 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_initial_fire_request_history(apps, schema_editor):
    FireDepartmentRequest = apps.get_model("requests_app", "FireDepartmentRequest")
    FireDepartmentRequestStatusHistory = apps.get_model("requests_app", "FireDepartmentRequestStatusHistory")
    history = [
        FireDepartmentRequestStatusHistory(
            request=request,
            old_status=None,
            new_status=request.status,
            completed_at=request.completed_at if request.status == "done" else None,
            changed_by=request.created_by,
            note="Создание заявки",
        )
        for request in FireDepartmentRequest.objects.filter(is_deleted=False)
    ]
    FireDepartmentRequestStatusHistory.objects.bulk_create(history, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_vehiclerepairrequest_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firealarm',
            options={'ordering': ('-state_date', '-created_at'), 'verbose_name': 'пожарная сигнализация', 'verbose_name_plural': 'Пожарная сигнализация'},
        ),
        migrations.AlterModelOptions(
            name='fireextinguisher',
            options={'ordering': ('-state_date', 'expiry_date', '-created_at'), 'verbose_name': 'огнетушитель', 'verbose_name_plural': 'Огнетушители'},
        ),
        migrations.AlterModelOptions(
            name='securityalarm',
            options={'ordering': ('-state_date', '-created_at'), 'verbose_name': 'охранная сигнализация', 'verbose_name_plural': 'Охранная сигнализация'},
        ),
        migrations.AddField(
            model_name='firealarm',
            name='state_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='firedepartmentrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки'),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='state_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='securityalarm',
            name='state_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='firealarm',
            name='broken_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='объектов с неисправной ПС'),
        ),
        migrations.AlterField(
            model_name='firealarm',
            name='equipped_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='оборудовано ПС объектов'),
        ),
        migrations.AlterField(
            model_name='firealarm',
            name='required_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='подлежит оборудованию ПС'),
        ),
        migrations.AlterField(
            model_name='securityalarm',
            name='broken_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='объектов с неисправной ОС'),
        ),
        migrations.AlterField(
            model_name='securityalarm',
            name='equipped_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='оборудовано ОС объектов'),
        ),
        migrations.AlterField(
            model_name='securityalarm',
            name='required_objects',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='подлежит оборудованию ОС'),
        ),
        migrations.CreateModel(
            name='FireDepartmentRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, null=True, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, verbose_name='новый статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата изменения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_department_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.firedepartmentrequest', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'изменение статуса заявки пожарной безопасности',
                'verbose_name_plural': 'История статусов заявок пожарной безопасности',
                'ordering': ('-changed_at', '-id'),
                'indexes': [models.Index(fields=['request', '-changed_at'], name='requests_ap_request_766d96_idx')],
            },
        ),
        migrations.RunPython(create_initial_fire_request_history, migrations.RunPython.noop),
    ]
