# Generated by Django 5.2.15 on 2026-06-27 05:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialize_anti_terror_requests(apps, schema_editor):
    AntiTerrorMeasure = apps.get_model("requests_app", "AntiTerrorMeasure")
    AntiTerrorMeasureStatusHistory = apps.get_model("requests_app", "AntiTerrorMeasureStatusHistory")
    history = []
    for request in AntiTerrorMeasure.objects.filter(is_deleted=False):
        if not request.request_number:
            request.request_number = str(request.pk)
            request.save(update_fields=["request_number"])
        history.append(
            AntiTerrorMeasureStatusHistory(
                request=request,
                old_status=None,
                new_status=request.status,
                completed_at=request.completed_at if request.status == "done" else None,
                changed_by=request.created_by,
                note="Создание заявки",
            )
        )
    AntiTerrorMeasureStatusHistory.objects.bulk_create(history, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_alter_firealarm_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antiterrormeasure',
            options={'ordering': ('-request_date', '-created_at'), 'verbose_name': 'антитеррористическая укрепленность', 'verbose_name_plural': 'Антитеррористическая укрепленность'},
        ),
        migrations.AddField(
            model_name='antiterrormeasure',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки'),
        ),
        migrations.AddField(
            model_name='antiterrormeasure',
            name='request_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='antiterrormeasure',
            name='request_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='funding_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='потребность финансирования'),
        ),
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='measure',
            field=models.TextField(blank=True, default='', verbose_name='мероприятие'),
        ),
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=20, verbose_name='исполнение'),
        ),
        migrations.CreateModel(
            name='AntiTerrorMeasureStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, null=True, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, verbose_name='новый статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата изменения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anti_terror_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.antiterrormeasure', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'изменение статуса заявки антитеррористической укрепленности',
                'verbose_name_plural': 'История статусов заявок антитеррористической укрепленности',
                'ordering': ('-changed_at', '-id'),
                'indexes': [models.Index(fields=['request', '-changed_at'], name='requests_ap_request_3f803c_idx')],
            },
        ),
        migrations.RunPython(initialize_anti_terror_requests, migrations.RunPython.noop),
    ]
