# Generated by Django 5.2.15 on 2026-06-27 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialize_citsizi_requests(apps, schema_editor):
    CitsiziEquipment = apps.get_model("requests_app", "CitsiziEquipment")
    CitsiziEquipmentStatusHistory = apps.get_model("requests_app", "CitsiziEquipmentStatusHistory")
    history = []
    for request in CitsiziEquipment.objects.filter(is_deleted=False):
        update_fields = []
        if not request.request_number:
            request.request_number = str(request.pk)
            update_fields.append("request_number")
        if update_fields:
            request.save(update_fields=update_fields)
        history.append(
            CitsiziEquipmentStatusHistory(
                request=request,
                old_status=None,
                new_status=request.status,
                completed_at=request.due_date if request.status == "done" else None,
                changed_by=request.created_by,
                note="Создание заявки",
            )
        )
    CitsiziEquipmentStatusHistory.objects.bulk_create(history, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_alter_antiterrormeasure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citsiziequipment',
            options={'ordering': ('-request_date', '-created_at'), 'verbose_name': 'заявка ЦИТСиЗИ', 'verbose_name_plural': 'По линии ЦИТСиЗИ'},
        ),
        migrations.AddField(
            model_name='citsiziequipment',
            name='request_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='citsiziequipment',
            name='request_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='equipment_name',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='наименование'),
        ),
        migrations.CreateModel(
            name='CitsiziEquipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, null=True, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, verbose_name='новый статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата изменения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citsizi_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.citsiziequipment', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'изменение статуса заявки ЦИТСиЗИ',
                'verbose_name_plural': 'История статусов заявок ЦИТСиЗИ',
                'ordering': ('-changed_at', '-id'),
                'indexes': [models.Index(fields=['request', '-changed_at'], name='requests_ap_request_3180ec_idx')],
            },
        ),
        migrations.RunPython(initialize_citsizi_requests, migrations.RunPython.noop),
    ]
