# Generated by Django 5.2.15 on 2026-06-27 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_initial_building_repair_history(apps, schema_editor):
    BuildingRepairRequest = apps.get_model("requests_app", "BuildingRepairRequest")
    BuildingRepairRequestStatusHistory = apps.get_model("requests_app", "BuildingRepairRequestStatusHistory")
    history = [
        BuildingRepairRequestStatusHistory(
            request=request,
            old_status=None,
            new_status=request.status,
            completed_at=request.completed_at if request.status == "done" else None,
            changed_by=request.created_by,
            note="Создание заявки",
        )
        for request in BuildingRepairRequest.objects.filter(is_deleted=False)
    ]
    BuildingRepairRequestStatusHistory.objects.bulk_create(history, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0011_alter_citsiziequipment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehousing',
            options={'ordering': ('-state_date', '-created_at'), 'verbose_name': 'служебное жилье', 'verbose_name_plural': 'Служебное жилье'},
        ),
        migrations.AddField(
            model_name='servicehousing',
            name='state_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата'),
        ),
        migrations.CreateModel(
            name='BuildingRepairRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, null=True, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], max_length=20, verbose_name='новый статус')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата изменения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_repair_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.buildingrepairrequest', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'изменение статуса заявки текущего ремонта',
                'verbose_name_plural': 'История статусов заявок текущего ремонта',
                'ordering': ('-changed_at', '-id'),
                'indexes': [models.Index(fields=['request', '-changed_at'], name='requests_ap_request_0b0494_idx')],
            },
        ),
        migrations.RunPython(create_initial_building_repair_history, migrations.RunPython.noop),
    ]
