# Generated by Django 5.2.15 on 2026-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0012_alter_servicehousing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrepairrequest',
            name='request_date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='buildingrepairrequest',
            name='request_number',
            field=models.CharField(max_length=80, verbose_name='номер'),
        ),
    ]
