# Generated by Django 5.2.15 on 2026-06-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("requests_app", "0013_alter_buildingrepairrequest_request_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antiterrormeasure",
            name="funding_required",
        ),
        migrations.RemoveField(
            model_name="antiterrormeasure",
            name="measure",
        ),
        migrations.RemoveField(
            model_name="antiterrormeasure",
            name="object_name",
        ),
        migrations.RemoveField(
            model_name="buildingrepairrequest",
            name="repair_object",
        ),
        migrations.RemoveField(
            model_name="buildingrepairrequest",
            name="work_description",
        ),
        migrations.RemoveField(
            model_name="citsiziequipment",
            name="equipment_name",
        ),
        migrations.RemoveField(
            model_name="servicehousing",
            name="status",
        ),
        migrations.CreateModel(
            name="RequestStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField(verbose_name="ID заявки")),
                ("old_status", models.CharField(blank=True, choices=[("new", "Новая"), ("in_work", "В работе"), ("done", "Исполнена"), ("rejected", "Отклонена")], max_length=20, null=True, verbose_name="предыдущий статус")),
                ("new_status", models.CharField(choices=[("new", "Новая"), ("in_work", "В работе"), ("done", "Исполнена"), ("rejected", "Отклонена")], max_length=20, verbose_name="новый статус")),
                ("completed_at", models.DateField(blank=True, null=True, verbose_name="дата исполнения")),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="дата изменения")),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="примечание")),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="request_status_changes", to=settings.AUTH_USER_MODEL, verbose_name="изменил")),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype", verbose_name="тип заявки")),
            ],
            options={
                "verbose_name": "изменение статуса заявки",
                "verbose_name_plural": "История статусов заявок",
                "ordering": ("-changed_at", "-id"),
            },
        ),
        migrations.DeleteModel(
            name="AntiTerrorMeasureStatusHistory",
        ),
        migrations.DeleteModel(
            name="BuildingRepairRequestStatusHistory",
        ),
        migrations.DeleteModel(
            name="CitsiziEquipmentStatusHistory",
        ),
        migrations.DeleteModel(
            name="FireDepartmentRequestStatusHistory",
        ),
        migrations.DeleteModel(
            name="FireSafetyRequest",
        ),
        migrations.DeleteModel(
            name="TmcNeed",
        ),
        migrations.DeleteModel(
            name="TmcRequestStatusHistory",
        ),
        migrations.DeleteModel(
            name="TransportRequest",
        ),
        migrations.DeleteModel(
            name="VehicleRepairRequestStatusHistory",
        ),
        migrations.AddIndex(
            model_name="requeststatushistory",
            index=models.Index(fields=["content_type", "object_id", "-changed_at"], name="requests_ap_content_86bb0c_idx"),
        ),
    ]
