# Generated by Django 5.2.15 on 2026-06-27 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0014_cleanup_legacy_request_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='request_number',
            field=models.CharField(max_length=80, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='request_number',
            field=models.CharField(max_length=80, verbose_name='номер'),
        ),
    ]
