# Generated by Django 5.2.15 on 2026-06-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0015_alter_antiterrormeasure_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citsiziequipment',
            name='equipment_type',
            field=models.CharField(choices=[('communication', 'Средства связи'), ('organizational', 'Организационная техника'), ('computing', 'Вычислительная техника'), ('special', 'Специальная техника'), ('video', 'Видеонаблюдение'), ('sound_alert', 'Система звукового оповещения')], db_index=True, max_length=30, verbose_name='тип техники'),
        ),
    ]
