# Generated by Django 5.2.15 on 2026-06-29 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0006_remove_territorialorganphotofolder_unique_root_photo_folder_per_organ_and_more'),
        ('requests_app', '0016_alter_citsiziequipment_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhotoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип заявки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_request_photo_links', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_links', to='directory.territorialorganphoto', verbose_name='фотография')),
                ('territorial_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_photo_links', to='directory.territorialorgan', verbose_name='территориальный орган')),
            ],
            options={
                'verbose_name': 'связь заявки с фотографией',
                'verbose_name_plural': 'Связи заявок с фотографиями',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['territorial_organ', 'content_type', 'object_id'], name='requests_ap_territo_1b6507_idx'), models.Index(fields=['photo', 'content_type', 'object_id'], name='requests_ap_photo_i_531c93_idx')],
                'constraints': [models.UniqueConstraint(fields=('photo', 'content_type', 'object_id'), name='unique_request_photo_link')],
            },
        ),
    ]
