# Generated by Django 5.2.15 on 2026-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0017_requestphotolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='buildingrepairrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='firealarm',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='firedepartmentrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='securityalarm',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='servicehousing',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tmcrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vehicleinventory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vehiclerepairrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
