# Generated by Django 5.2.15 on 2026-06-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_remove_territorialorganphotofolder_unique_root_photo_folder_per_organ_and_more'),
        ('requests_app', '0018_alter_antiterrormeasure_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFuelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='удалено')),
                ('comment', models.TextField(blank=True, verbose_name='описание')),
                ('request_number', models.CharField(max_length=80, verbose_name='номер')),
                ('request_date', models.DateField(verbose_name='дата')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Исполнена'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=20, verbose_name='исполнение заявки')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='дата исполнения заявки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('territorial_organ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='directory.territorialorgan', verbose_name='территориальный орган')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='обновил')),
            ],
            options={
                'verbose_name': 'заявка на ГСМ',
                'verbose_name_plural': 'Заявки на ГСМ',
                'ordering': ('-request_date',),
            },
        ),
    ]
