# Generated by Django 5.2.15 on 2026-06-29 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0019_vehiclefuelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='наименование')),
                ('normalized_name', models.CharField(db_index=True, max_length=180, unique=True, verbose_name='нормализованное наименование')),
                ('unit', models.CharField(default='шт.', max_length=40, verbose_name='единица измерения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'товар ТМЦ',
                'verbose_name_plural': 'Справочник товаров ТМЦ',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='tmcrequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='requests_app.tmcproduct', verbose_name='товар'),
        ),
    ]
