# Generated by Django 5.2.15 on 2026-07-07 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0024_request_number_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='antiterrormeasure',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_7898fa_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrepairrequest',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_519827_idx'),
        ),
        migrations.AddIndex(
            model_name='firedepartmentrequest',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_5e4196_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefuelrequest',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_5398c2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerepairrequest',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_7c5cf1_idx'),
        ),
    ]
