# Generated by Django 5.2.15 on 2026-07-08 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requests_app', '0025_antiterrormeasure_requests_ap_territo_7898fa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requeststatushistory',
            index=models.Index(fields=['content_type', 'new_status', 'changed_at'], name='requests_ap_content_b26a22_idx'),
        ),
    ]
