# Generated by Django 5.2.15 on 2026-07-09 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0026_requeststatushistory_requests_ap_content_b26a22_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='firealarm',
            index=models.Index(fields=['territorial_organ', 'state_date'], name='requests_ap_territo_deefe7_idx'),
        ),
        migrations.AddIndex(
            model_name='fireextinguisher',
            index=models.Index(fields=['territorial_organ', 'state_date'], name='requests_ap_territo_ae0bca_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalarm',
            index=models.Index(fields=['territorial_organ', 'state_date'], name='requests_ap_territo_f54fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicehousing',
            index=models.Index(fields=['territorial_organ', 'state_date'], name='requests_ap_territo_c35b60_idx'),
        ),
    ]
