# Generated by Django 5.2.15 on 2026-07-09 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0027_firealarm_requests_ap_territo_deefe7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citsiziequipment',
            index=models.Index(fields=['territorial_organ', 'request_date', 'status'], name='requests_ap_territo_ab2f7d_idx'),
        ),
    ]
