# Generated by Django 5.2.15 on 2026-07-09 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0028_citsiziequipment_requests_ap_territo_ab2f7d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='firealarm',
            name='requests_ap_territo_deefe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='fireextinguisher',
            name='requests_ap_territo_ae0bca_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalarm',
            name='requests_ap_territo_f54fe9_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicehousing',
            name='requests_ap_territo_c35b60_idx',
        ),
        migrations.AddIndex(
            model_name='firealarm',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'state_date', 'created_at'], name='requests_ap_territo_be0215_idx'),
        ),
        migrations.AddIndex(
            model_name='fireextinguisher',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'state_date', 'created_at'], name='requests_ap_territo_831c91_idx'),
        ),
        migrations.AddIndex(
            model_name='fireextinguisher',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'expiry_date'], name='requests_ap_territo_50bb90_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalarm',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'state_date', 'created_at'], name='requests_ap_territo_36566a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicehousing',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'state_date', 'created_at'], name='requests_ap_territo_81a847_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinventory',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'state_date', 'created_at'], name='requests_ap_territo_cd5a2d_idx'),
        ),
    ]
