# Generated by Django 5.2.15 on 2026-07-10 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requests_app', '0029_remove_firealarm_requests_ap_territo_deefe7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requeststatushistory',
            index=models.Index(fields=['content_type', 'new_status', 'object_id'], name='requests_ap_content_020e96_idx'),
        ),
    ]
