# Generated by Django 5.2.15 on 2026-07-10 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0030_requeststatushistory_requests_ap_content_020e96_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='antiterrormeasure',
            name='requests_ap_territo_7898fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='buildingrepairrequest',
            name='requests_ap_territo_519827_idx',
        ),
        migrations.RemoveIndex(
            model_name='citsiziequipment',
            name='requests_ap_territo_d13f13_idx',
        ),
        migrations.RemoveIndex(
            model_name='citsiziequipment',
            name='requests_ap_territo_ab2f7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='firedepartmentrequest',
            name='requests_ap_territo_5e4196_idx',
        ),
        migrations.RemoveIndex(
            model_name='tmcrequest',
            name='requests_ap_territo_73a786_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclefuelrequest',
            name='requests_ap_territo_5398c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclerepairrequest',
            name='requests_ap_territo_7c5cf1_idx',
        ),
        migrations.AddIndex(
            model_name='antiterrormeasure',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_98ba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrepairrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_86ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='citsiziequipment',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'equipment_type'], name='requests_ap_territo_7ee4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='citsiziequipment',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_ae49da_idx'),
        ),
        migrations.AddIndex(
            model_name='firedepartmentrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_785fce_idx'),
        ),
        migrations.AddIndex(
            model_name='tmcrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_1b73e1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefuelrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_12af35_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerepairrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', 'request_date', 'status'], name='requests_ap_territo_198067_idx'),
        ),
    ]
