# Generated by Django 5.2.15 on 2026-07-10 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0032_postgresql_trigram_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='antiterrormeasure',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_f6b655_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingrepairrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_6425e4_idx'),
        ),
        migrations.AddIndex(
            model_name='firedepartmentrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_58f472_idx'),
        ),
        migrations.AddIndex(
            model_name='tmcrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_d92bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefuelrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_d1cd47_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerepairrequest',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_a42503_idx'),
        ),
    ]
