# Generated by Django 5.2.15 on 2026-07-10 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_territorialorganphoto_thumbnails'),
        ('requests_app', '0033_pagination_ordering_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citsiziequipment',
            index=models.Index(fields=['territorial_organ', 'is_deleted', '-request_date', '-created_at', '-id'], name='requests_ap_territo_1099ea_idx'),
        ),
    ]
