# Generated by Django 5.2.15 on 2026-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0035_alter_antiterrormeasure_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiterrormeasure',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='buildingrepairrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='citsiziequipment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='firedepartmentrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='tmcrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='vehiclefuelrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
        migrations.AlterField(
            model_name='vehiclerepairrequest',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата исполнения'),
        ),
    ]
