# Generated by Django 5.2.15 on 2026-07-23 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


TRIGRAM_INDEXES = (
    ("rq_response_num_trgm", "response_number"),
    ("rq_response_note_trgm", "note"),
)


def create_postgresql_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.quote_name
    table = "requests_app_requestresponse"
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for name, column in TRIGRAM_INDEXES:
        schema_editor.execute(
            f"CREATE INDEX IF NOT EXISTS {quote(name)} ON {quote(table)} "
            f"USING gin ({quote(column)} gin_trgm_ops)"
        )


def drop_postgresql_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.quote_name
    for name, _column in reversed(TRIGRAM_INDEXES):
        schema_editor.execute(f"DROP INDEX IF EXISTS {quote(name)}")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requests_app', '0036_alter_antiterrormeasure_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID заявки')),
                ('response_number', models.CharField(max_length=80, verbose_name='номер ответа')),
                ('normalized_response_number', models.CharField(editable=False, max_length=80, verbose_name='нормализованный номер ответа')),
                ('response_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='дата ответа')),
                ('response_type', models.CharField(choices=[('interim', 'Промежуточный'), ('final', 'Итоговый')], max_length=20, verbose_name='тип ответа')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип заявки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_responses_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_responses_updated', to=settings.AUTH_USER_MODEL, verbose_name='обновил')),
            ],
            options={
                'verbose_name': 'ответ на заявку',
                'verbose_name_plural': 'Ответы на заявки',
                'ordering': ('-response_date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['content_type', 'object_id', '-response_date', '-created_at'], name='request_response_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'normalized_response_number'), name='unique_response_document_per_request')],
            },
        ),
        migrations.RunPython(create_postgresql_indexes, drop_postgresql_indexes),
    ]
